[package]
name = "proc-core"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.23"
graphviz-rust = "0.9.8"
itertools = "0.15"
nalgebra = "0.35"
serde = { version = "1.0.228", features = ["derive", "rc"] }
serde_json = { version = "1.0.149", default-features = false, features = ["alloc"] }

enum-id = {path = "../enum-id"}
enum-id-derive = {path = "../enum-id-derive"}
regex = "1.12.3"

[dev-dependencies]
approx = { version = "0.5.1" }
tracing-subscriber = { version = "0.3.23" }
